# Generated by Django 5.1.2 on 2024-10-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('proposal', '提案中'), ('ongoing', '進行中'), ('waiting', '結果待ち'), ('confirmed', '確定'), ('failure', '失敗')], default='proposal', max_length=20),
        ),
    ]
