# Generated by Django 5.1.2 on 2024-10-17 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='better_skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='content_match',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='業務内容合致度'),
        ),
        migrations.AddField(
            model_name='project',
            name='environment_match',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='就業環境合致度'),
        ),
        migrations.AddField(
            model_name='project',
            name='must_skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('proposal', '提案中'), ('ongoing', '進行中'), ('interview', '面談'), ('waiting', '結果待ち'), ('join', '確定')], default='proposal', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
