# Generated by Django 5.1.2 on 2024-10-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_better_skill_project_content_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='time',
            new_name='work_time',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('proposal', '提案'), ('ongoing', '進行中'), ('interview', '面談'), ('waiting', '結果待ち'), ('join', '確定')], default='proposal', max_length=20),
        ),
    ]
