# Generated by Django 5.1.2 on 2024-10-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_address_alter_project_better_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('proposal', '提案中'), ('offering', '営業中'), ('interview', '面談'), ('waiting', '結果待ち'), ('join', '確定'), ('decline', '辞退')], default='proposal', max_length=20, verbose_name='状態'),
        ),
    ]
