# Generated by Django 5.1.2 on 2024-10-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='better_skill',
        ),
        migrations.RemoveField(
            model_name='project',
            name='must_skill',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_period',
        ),
        migrations.RemoveField(
            model_name='project',
            name='work_time',
        ),
        migrations.AddField(
            model_name='project',
            name='impressions',
            field=models.TextField(blank=True, null=True, verbose_name='面談後所感'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='技術スタック'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('offering', '営業中'), ('interview', '面談待ち'), ('waiting', '結果待ち'), ('success', '採用確定'), ('decline', '辞退')], default='proposal', max_length=20, verbose_name='状態'),
        ),
    ]
