# Generated by Django 5.1.2 on 2024-10-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_better_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('offering', '営業中'), ('interview', '面談待ち'), ('waiting', '結果待ち'), ('rejection', '落選'), ('decline', '辞退'), ('success', '採用確定')], default='proposal', max_length=20, verbose_name='状態'),
        ),
    ]
